name: Super Linter

on:
  push:
    branches:
      - main  # specify the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # specify the branch you want to trigger the workflow on

jobs:
  super-linter:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Super Linter
        uses: github/super-linter@v4
        with:
          lint-check: 'true'
          validation: 'true'
          strict: 'true'
          # Additional configuration options as needed
          
      - name: Set up GitHub token
        run: echo "${{ secrets.GITHUB_TOKEN }}" > GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Super Linter with GitHub token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker-compose run -e GITHUB_TOKEN -e VALIDATE_ALL_CODEBASE validate-all-codebase
