name: Linter

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    - name: Install dependencies
      run: npm ci 

    - name: Run linter
      run: npm run lint 

    - name: Create pull request
      if: success() 
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GIT_TOKEN }} # Required for creating pull request
        branch: lint-fixes 
        commit-message: "Fix linting issues"
        title: "Fix linting issues"
        body: "This pull request fixes linting issues found in the code."

    - name: Merge pull request
      if: success() 
      uses: pullreminders/merge-action@v5
      with:
        token: ${{ secrets.GIT_TOKEN }}
        pull_request: ${{ steps.create_pull_request.outputs.pull_request_number }} # Reference to the created pull request

    - name: Delete branch
      if: success() 
      run: |
        git checkout master 
        git branch -d lint-fixes 
        
