name: Linter

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    - name: Super-Linter
      uses: github/super-linter@v5.0.0

  
